<? echo View::partial("katalogo/header_usuario") ?>


<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2">
            <? echo View::partial("katalogo/menu_usuario") ?>
        </div>
        <div class="span10">
            <h2>Nuevo Usuario</h2>

            <div>
                <div><? echo View::content() ?></div>
                <div><? echo Form::open() ?></div>

                <div><? echo Form::label("Nombre:", "nombre") ?></div>
                <div><? echo Form::text('usuarios.nombre') ?></div>
                
                <div><? echo Form::label("Apellido:", "apellido") ?></div>
                <div><? echo Form::text('usuarios.apellido') ?></div>
                
                <div><? echo Form::label("Dirección:", "direccion") ?></div>
                <div><? echo Form::text('usuarios.direccion') ?></div>
                
                <div><? echo Form::label("Telefono:", "telefono") ?></div>
                <div><? echo Form::text('usuarios.telefono') ?></div>
                
                <div><? echo Form::label("Login:", "login") ?></div>
                <div><? echo Form::text('usuarios.login') ?></div>
                
                <div><? echo Form::label("Clave:", "clave") ?></div>
                <div><? echo Form::pass('usuarios.clave') ?></div>
                
                <div><? echo Form::label("Tipo Usuario:", "tipousuario_id") ?></div>
                <div><? echo Form::dbSelect('usuarios.tipousuario_id') ?></div>

                <? echo Form::submit("Crear", "class='btn btn-primary'") ?>

                <? echo Form::close() ?>

            </div>
        </div>
    </div>
</div>