
<?echo View::partial("katalogo/header_imagen")?>

<script>
    
    function abrir(id){
         var html= "<IMG SRC='"+id+"'>";
         $('#cambio').html(html);
         $('#myModal').modal('show');
    }
   
</script>
    


<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2">
           <?echo View::partial("katalogo/menu_imagen")?>
 

    <div class="modal hide fade" id="myModal">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Imagen</h3>
    </div>
    <div class="modal-body">
        <div id="cambio"></div>
    
    </div>
    <div class="modal-footer">
    
    </div>
    </div>
        </div>
        <div class="span10">
            
            <div>
                
                <?echo Form::open()?>
            
                <?echo Form::label("Categoria:","categoria")?>
                <select id="categoria" name="categoria">
                
                 <?while($combo = $combocategoria->fetchArray(SQLITE3_ASSOC)){?>
                    <?echo "<option value=".$combo["id"].">".$combo["nombre"]."</option>"?>
                 <?}?>
            
                </select>
                
                <?echo Form::submit("Buscar","class='btn btn-primary'")?>
                
                
                
                <?echo Form::close()?>
            
            </div>
            
            <table class="table table-bordered table-striped">

                <thead>
                <th>Id</th>
                <th>Imagen</th>
                <th>Ver imagen</th>
                <th>Categoria</th>
                <th>Fecha act</th>
                <th>Eliminar</th>
                <th>Modificar</th>
                <th>Rel productos</th>
                </thead>
<?

$i = 0;

    

while ($res = $result->fetchArray(SQLITE3_ASSOC)) {?>

                <tr>
                    <td>
            <?
                $id = $res['id'];
                echo $id;
                
                
            ?>

                    </td>
                    
                    <td>
            <?  
                
                file_put_contents("img/tempkatalogo/".$id.".jpg", $res['imagen']);
                $ruta = PUBLIC_PATH."img/";
                $imagen = $ruta.'/tempkatalogo/'.$id.'.jpg';
                echo Html::img("tempkatalogo/".$id.".jpg",$id,"height='50' width='50' data-zoomsrc='$imagen'");
            ?>
                    </td>
                    <td>
                        <button onclick="abrir('<?echo $imagen?>')">Abrir</button>
                    </td>
                    <td>
        <?echo $res['nombre']?>
                    </td>
                    <td>
        <?echo $res['fechaactualizacion']?>
                    </td>
                    <td>
                        <?echo Html::link("imagen/eliminar/$id","Eliminar")?>
                    </td>
                    <td><?echo Html::link("imagen/modificar/$id","Modificar")?>

                    </td>
                    <td><?echo Html::link("imagen/relacionar/$id","Relacionar")?>

                    </td>

                </tr>   

<?$i++;}?>

            </table>
            
        </div>
    </div>
</div>



