<table class="table-bordered">
    <thead>
    <th>id</th>
    <th>producto_id</th>
    <th>pedido_id</th>
    <th>cantidad</th>
    <th>descuento1</th>
    <th>descuento2</th>
    <th>precio</th>
    <th>observacion</th>
    </thead>
<?foreach($prods as $o){?>

    <tr>
        <td><?=$o->id?></td>
        <td><?=$o->producto_id?></td>
        
        <td><?
        $bd = Conexion::devolverCon();
        $result = $bd->query("select descripcion from misproductos where idproducto='$o->producto_id'");
        
        while($res = $result->fetchArray()){
            echo $res["descripcion"];
        }
        ?></td>
        <td><?=$o->pedido_id?></td>
        <td><?=$o->cantidad?></td>
        <td><?=$o->descuento1?></td>
        <td><?=$o->descuento2?></td>
        <td><?=$o->precio?></td>
        <td><?=$o->observacion?></td>
    </tr>

<? } ?>
</table>
