<? echo View::partial("katalogo/header_categoria") ?>


<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2">
            <? echo View::partial("katalogo/menu_categoria") ?>
        </div>
        <div class="span10">
            <h2>Nueva Categoria</h2>

            <div>
                <div><? echo View::content() ?></div>
                <div><? echo Form::open() ?></div>

                <div><? echo Form::label("Nombre:", "nombre") ?></div>
                <div><? echo Form::text('categorias.nombre') ?></div>
                
                <div><? echo Form::label("Fabricante:", "fabricante_id") ?></div>
                <div><? echo Form::dbSelect('categorias.fabricante_id') ?></div>

                <? echo Form::submit("Crear", "class='btn btn-primary'") ?>

                <? echo Form::close() ?>

            </div>


        </div>
    </div>
</div>